version: "3.9"
services:
  web:
    build: .
    container_name: Emapa-pago-agua
    ports:
      - "3000:3000"
              # opcional; crea este archivo si usas variables
    restart: unless-stopped
